[project]
name = "oracle-db-doc-mcp-server"
version = "0.1.0"
description = "The Oracle Database Documentation MCP Server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.9.0",
    "fastmcp>=2.11.3",
    "markdownify>=1.2.0",
    "pocketsearch>=0.40.0",
]
