name: ðŸ› ï¸ Build an image
on:
  push:
    paths:
      - 'src/oracle-db-mcp-server/**'
      - '.github/**'
  pull_request:
    paths:
      - 'src/oracle-db-mcp-server/**'

jobs:

  build-image:
    strategy:
      matrix:
        runner: [ "ubuntu-24.04", "ubuntu-24.04-arm" ]

    permissions:
      packages: write
    
    name: ðŸ› ï¸ Build image
    runs-on: ${{ matrix.runner }}

    steps:
      - name: ðŸ“‚ Checkout repo
        uses: actions/checkout@v4

      - name: ðŸ”„ Generate environment variables
        id: os_arch
        run: |
          if [ "$(uname -m)" == "aarch64" ]; then
            echo "OS_ARCH=arm64" >> "$GITHUB_OUTPUT"
          else
            echo "OS_ARCH=amd64" >> "$GITHUB_OUTPUT"
          fi;

      - name: Build image
        run: |
          cd src/oracle-db-mcp-server/
          buildah bud -f Dockerfile -t oracle-doc:latest-${{ steps.os_arch.outputs.OS_ARCH }} .


      - name: ðŸ”“ Login to GHCR registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: ðŸ«¸ Push image to Container Registry
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ghcr.io/gvenzl/mcp
          image: oracle-doc
          tags: latest-${{ steps.os_arch.outputs.OS_ARCH }}


  upload-multi-arch:
    name: ðŸ«¸ Push multi-arch manifest
    runs-on: "ubuntu-24.04"
    needs: build-image

    permissions:
      packages: write

    steps:
      - name: ðŸ«¸ Push multi-arch manifest
        run: |
          podman manifest create gvenzl/mcp/oracle-doc:latest
          podman manifest add    gvenzl/mcp/oracle-doc:latest  gvenzl/mcp/oracle-doc:latest-amd64
          podman manifest add    gvenzl/mcp/oracle-doc:latest  gvenzl/mcp/oracle-doc:latest-arm64
          podman push gvenzl/mcp/oracle-doc:latest
          
