name: ğŸ› ï¸ Build an image
on:
  push:
    paths:
      - 'src/oracle-db-mcp-server/**'
      - '.github/**'
  pull_request:
    paths:
      - 'src/oracle-db-mcp-server/**'

jobs:

  build-image:
    strategy:
      matrix:
        runner: [ "ubuntu-24.04", "ubuntu-24.04-arm" ]

    permissions:
      packages: write
    
    name: ğŸ› ï¸ Build image
    runs-on: ${{ matrix.runner }}

    steps:
      - name: ğŸ“‚ Checkout repo
        uses: actions/checkout@v4

      - name: ğŸ”„ Generate environment variables
        id: os_arch
        run: |
          if [ "$(uname -m)" == "aarch64"] ; then
            echo "OS_ARCH=arm64" >> "$GITHUB_OUTPUT"
          else
            echo "OS_ARCH=amd64" >> "$GITHUB_OUTPUT"
          fi;

      - name: â¬ Install build dependencies
        run: sudo apt-get install -y buildah

      - name: Build image
        run: |
          cd src/oracle-db-mcp-server/
          buildah bud -f Dockerfile -t oracle-doc-mcp:latest-${{ steps.os_arch.outputs.OS_ARCH }} .


      - name: ğŸ”“ Login to GHCR registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: ğŸ«¸ Push image to Container Registry
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ghcr.io/gvenzl/mcp
          image: oracle-doc-mcp
          tags: latest-${{ steps.os_arch.outputs.OS_ARCH }}
