name: ðŸ› ï¸ Build Docker image for Oracle Database Documentation MCP Server
on:
  push:
    paths:
      - "src/oracle-db-doc-mcp-server/**"
      - ".github/workflows/build-doc-mcp.yml"
  pull_request:
    paths:
      - "src/oracle-db-doc-mcp-server/**"
      - ".github/workflows/build-doc-mcp.yml"

jobs:
  build-image:
    strategy:
      matrix:
        runner: ["ubuntu-24.04", "ubuntu-24.04-arm"]

    permissions:
      packages: write

    name: ðŸ› ï¸ Build image
    runs-on: ${{ matrix.runner }}

    steps:
      - name: ðŸ“‚ Checkout repo
        uses: actions/checkout@v4

      - name: ðŸ”„ Generate environment variables
        id: os_arch
        run: |
          if [ "$(uname -m)" == "aarch64" ]; then
            echo "OS_ARCH=arm64" >> "$GITHUB_OUTPUT"
          else
            echo "OS_ARCH=amd64" >> "$GITHUB_OUTPUT"
          fi;

      - name: Build image
        run: |
          cd src/oracle-db-doc-mcp-server/
          buildah bud -f Dockerfile -t oracle-db-doc:latest-${{ steps.os_arch.outputs.OS_ARCH }} .

      - name: ðŸ«¸ Push arch-specific image to Container Registry
        run: |
          podman login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          podman tag oracle-db-doc:latest-${{ steps.os_arch.outputs.OS_ARCH }} ghcr.io/oracle/mcp/oracle-db-doc:latest-${{ steps.os_arch.outputs.OS_ARCH }}
          podman push ghcr.io/oracle/mcp/oracle-db-doc:latest-${{ steps.os_arch.outputs.OS_ARCH }}

  upload-multi-arch:
    name: ðŸ«¸ Push multi-arch manifest
    runs-on: "ubuntu-24.04"
    needs: build-image

    permissions:
      packages: write

    steps:
      - name: ðŸ«¸ Push multi-arch image to Container Registry
        run: |
          podman login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          podman manifest create ghcr.io/oracle/mcp/oracle-db-doc:latest
          podman manifest add    ghcr.io/oracle/mcp/oracle-db-doc:latest  ghcr.io/oracle/mcp/oracle-db-doc:latest-amd64
          podman manifest add    ghcr.io/oracle/mcp/oracle-db-doc:latest  ghcr.io/oracle/mcp/oracle-db-doc:latest-arm64
          podman push ghcr.io/oracle/mcp/oracle-db-doc:latest
